- name: Create sysadmins group and add user ktierney on the localhost
  hosts: localhost
  connection: local 

  tasks:
    - name: Ensure sysadmins group exists
      group:
        name: sysadmins
        state: present

    - name: Create user ktierney
      user:
        name: ktierney
        state: present
        groups: sysadmins